# Generated by Django 5.2.7 on 2025-10-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('material', models.CharField(max_length=100, verbose_name='Материал')),
                ('diameter', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Диаметр (мм)')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('weight', models.PositiveIntegerField(verbose_name='Вес катушки (г)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена (₽)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Остаток на складе')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Филамент',
                'verbose_name_plural': 'Филаменты',
                'ordering': ['brand', 'material', 'color'],
            },
        ),
    ]
