# Generated by Django 5.2.7 on 2025-10-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filament',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='filaments/', verbose_name='Изображение'),
        ),
    ]
